### ISSUE TITLE
User story: Add articles for user to view on home page

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#11]
Epic: #10 

As a user, I want to be able to pick and view articles that interest me so I can plan a trip.

Tasks :
* [x] Add data to the database
* [x] Create a card to display articles 
* [x] Shows article information like the title and a small description of the article

Acceptance Criteria:

- Data is added to the database
- Create cards on the home page to display the data
- Users can see the articles being displayed.
