### ISSUE TITLE
User Story: Add images to cards and articles 

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#12]
Epic: #10 

As a user, I want to be able to see images of the places I want to view so that I can get a picture of what they are like

Tasks :
* [x] Add images to the database
* [x] Set up Cloudinary for images
* [x] Add images to the cards 
* [x] Shows images alongside description and articles

Acceptance Criteria:

- Images are add to the database
- Add images to the cards.
- Users can see the images being displayed.
