### ISSUE TITLE
User Story: Help center for users

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#15]
Epic: #10 

As a user, I want to be able to contact the help center when I have an issue so that I can get it resolved.

Tasks:

* [x]  Add button to footer
* [x]  Button will open up a modal
* [x] Modal display contact information

Acceptance Criteria:

- User can click the button in the footer
- User can see a modal open
- User can see contact information
