### ISSUE TITLE
User Story: Create details page

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#17]
Epic: #16 

As a user, I want to see the Details page clearly so that it is easy to find information.

Tasks:

* [x] Create details page
* [x] Set URL arguments
* [x] Set 404 Error page
* [x] Create model
* [x] Add content to database
* [x] Add images to the database

Acceptance Criteria:

- User can open the details page.
- User can view an error message if there is a 404 response.
- User can see images.
- User can see content that has been added.
