### ISSUE TITLE
User Story: Add reviews

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#18]
Epic: #16 

As a user, I want to add reviews so that people can see them.

Tasks:

* [x] In the details page create a button for adding reviews
* [x] When the button is clicked the new page for writing a review is opened
* [x] Create a new review page
* [x] Create submit review button
* [x] Create a modal for review
* [x] Save review to the database

Acceptance Criteria:

- User can click a button on the details page.
- Users can see a new page to add reviews.
- User can write a review.
- User review will be saved.
- User review can be seen on the details page.
