### ISSUE TITLE
User Story: Create About page

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#19]
Epic: #16 

As a user, I want to see the About page so that I can learn more about the website.

Tasks:

* [x] Add new App called about
* [x] Create a database for this page
* [x] Add data to the database
* [x] Create the About page
* [x] Link the About page to the navigation bar

Acceptance Criteria:

- User can see the about page.
- User can get to the About page from the navigation page.
- User can view data on the about page
