### ISSUE TITLE
User story:  Create the initial project structure

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#2]
Epic #1 

As a Developer,  I want to create the project structure so that I can develop the Rate Your Stay website.

Tasks:
* [x] Create a new project
* [x] Install Django
* [x] Create a new app
* [x] Create Heroku and deploy
* [x] Create PostgreSQL instance
* [x] Connect a database to code
* [x] Enter data into the database
* [x] Deploy the project
* [x] Connect Heroku to the PostgreSQL database

Acceptance Criteria:
- Frontend and Backend of the project are created
- The database is connected  to the project
- The project  is deployed on Heroku
