### ISSUE TITLE
User Story: Login to website

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#21]
Epic: #20 

As a user, I want to be able to log in and log out of the website so I can add reviews

Tasks:

* [x]  Install django-allauth
* [x]  Create Login template
* [x]  Create Logout template
* [x]  Add to base.html

Acceptance criteria:

- As a user, I can log in to the website and view the different pages.
- As a user, I can log out the website
