### ISSUE TITLE
User Story: Project clean up

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#25]
Epic: #24 

As a developer, I want to tidy up the project and make sure it meets all the requirements.

* [x] Check Spelling and syntax
* [x] Adjust responsive design
* [x] Final visual updates
* [x] Final functionality updates
* [x] Fix errors
* [x] Add any additional items that might have been overlooked and update any improvements.
* [x] Testing
* [x] Create Readme

Acceptance criteria

- Project is complete.
- Readme is complete.
