### ISSUE TITLE
User Story: Understand what the website is and what its user for

### ISSUE THREAD

**Issue by Chikayo-k** [Chikayo-k/rate-your-stay#4]
Epic: #3 

As a user, I want to understand what the website is at a glance.

Tasks:

* [x] Design the basic outline of the landing page
* [x] Create a leading message to show the user what the website is for.
* [x] Create Register and log In buttons on the hero image for easy navigation 

Acceptance Criteria:

1. The User opens up the website and sees the landing page.
2. The User can see a leading message on the screen.
3. The User can see register and log In buttons
